language: go

go:
  - 1.8.x
  - tip

sudo: required
cache:
  directories:
    - "daptinweb/node_modules"

services:
  - docker

script: go get github.com/GeertJohan/go.rice/rice && ls -lah && curl https://glide.sh/get | sh && glide install && cd daptinweb && npm install && npm run build && cd .. && rice embed-go && ls -lah && go build -ldflags='-extldflags "-static"' -o main && mkdir docker_dir && cp ./main ./docker_dir/main && cp Dockerfile docker_dir/Dockerfile


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    cp Dockerfile docker_dir/Dockerfile && cd docker_dir && docker build -t daptin/daptin:travis . && cd ..;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push daptin/daptin:travis;
    fi
  - go get -t ./... && go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)
  - cat /home/travis/gopath/src/github.com/daptin/daptin/coverage.txt

notifications:
  email: false